/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { InterestService } from "../interest.service";
import { InterestCreateInput } from "./InterestCreateInput";
import { Interest } from "./Interest";
import { InterestFindManyArgs } from "./InterestFindManyArgs";
import { InterestWhereUniqueInput } from "./InterestWhereUniqueInput";
import { InterestUpdateInput } from "./InterestUpdateInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class InterestControllerBase {
  constructor(protected readonly service: InterestService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Interest })
  async createInterest(
    @common.Body() data: InterestCreateInput
  ): Promise<Interest> {
    return await this.service.createInterest({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Interest] })
  @ApiNestedQuery(InterestFindManyArgs)
  async interests(@common.Req() request: Request): Promise<Interest[]> {
    const args = plainToClass(InterestFindManyArgs, request.query);
    return this.service.interests({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Interest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async interest(
    @common.Param() params: InterestWhereUniqueInput
  ): Promise<Interest | null> {
    const result = await this.service.interest({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Interest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateInterest(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() data: InterestUpdateInput
  ): Promise<Interest | null> {
    try {
      return await this.service.updateInterest({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Interest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteInterest(
    @common.Param() params: InterestWhereUniqueInput
  ): Promise<Interest | null> {
    try {
      return await this.service.deleteInterest({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/users")
  @ApiNestedQuery(UserFindManyArgs)
  async findUsers(
    @common.Req() request: Request,
    @common.Param() params: InterestWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUsers(params.id, {
      ...query,
      select: {
        age: true,
        agePreference: true,
        createdAt: true,
        email: true,
        firstName: true,
        id: true,

        interest: {
          select: {
            id: true,
          },
        },

        lastName: true,
        location: true,
        radiusPreference: true,
        roles: true,
        status: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/users")
  async connectUsers(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        connect: body,
      },
    };
    await this.service.updateInterest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/users")
  async updateUsers(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        set: body,
      },
    };
    await this.service.updateInterest({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/users")
  async disconnectUsers(
    @common.Param() params: InterestWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      users: {
        disconnect: body,
      },
    };
    await this.service.updateInterest({
      where: params,
      data,
      select: { id: true },
    });
  }
}
